# This file is used for building binaries using task release:build.
# Development env is handled by the flake, so we don't use this.
[toolchain]
channel = "1.91.1"
components = ["clippy"]
targets = [
  "aarch64-apple-darwin",
  "aarch64-unknown-linux-gnu",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
]
profile = "minimal"
